### ISSUE TITLE
Variables are not Modified

### ISSUE THREAD

**Issue by piranha87** [1and1/snmpman#21]
The result of the snmp walk of randomized values is only randomized once at application startup. In any other case it remains constant. 
But it should change on every snmp walk. 
I discovered that this issue first appeared after the class MOGroup was deleted in commit 78675aa0bdd385902c24462ca85975aeba0f3552

**Comment by sfuhrm** [comment]
Merged your request. 
This also fixes another bug.
Thank you, @piranha87 !
